# Numpy

There is no practise for this, basics..

In [9]:
import numpy as np

a = np.array([[3,4,5],[7,8,9]], dtype='float32')

# Display the array 'a'
print(a)

# Shape of the array, (2, 3)
print(a.shape)

# Number of dimensions, 2
print(a.ndim)

# Number of elements, 6
print(a.size)

# Data type of the array, float32
print(a.dtype)

# Accessing and printing element at row 0, column 1, output: [4.]
print(a[0,1])

# Create and display a 2x3 array filled with zeros
print(np.zeros((2,3)))

# Create and display a 2x3 array filled with ones
print(np.ones((2,3)))

# Create and display a 2x3 array filled with the value 99
print(np.full((2,3), 99))

# Create and display an array with the same shape as 'a', filled with 99
print(np.full_like(a.shape, 99))

# Create and display a 2x3 array with random values between 0 and 1
print(np.random.rand(2,3))

# Create and display a 3x3 array with random integers between -3 and 3
print(np.random.randint(-3, 3, (3,3)))

# Create and display a 3x3 identity matrix
print(np.identity(3))

# Repeat elements of 'a' 3 times along columns
print(np.repeat(a,3, axis=1))

# Create and display an array of values from 0 to 2
print(np.arange(0,2,1))

# Create and display an array with 3 linearly spaced values between 0 and 50
print(np.linspace(0,50,3))

# Find and display the minimum value along each row in 'a'
print(np.min(a, axis=1))

# Sum values along each column in 'a'
print(np.sum(a, axis=0))

# Reshape 'a' into a 3D array with shape (1, 2, 3)
print(a.reshape(1,2,3))

# Vertically stack two arrays 'a' on top of each other
print(np.vstack([a,a]))

# Horizontally stack two arrays 'a' side by side
print(np.hstack([a,a]))


[[3. 4. 5.]
 [7. 8. 9.]]
(2, 3)
2
6
float32
4.0
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[99 99 99]
 [99 99 99]]
[99 99]
[[0.30949956 0.89574634 0.74392438]
 [0.62222276 0.8639402  0.82650786]]
[[ 2  2  2]
 [ 0 -3  1]
 [ 0 -1 -2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 3. 3. 4. 4. 4. 5. 5. 5.]
 [7. 7. 7. 8. 8. 8. 9. 9. 9.]]
[0 1]
[ 0. 25. 50.]
[3. 7.]
[10. 12. 14.]
[[[3. 4. 5.]
  [7. 8. 9.]]]
[[3. 4. 5.]
 [7. 8. 9.]
 [3. 4. 5.]
 [7. 8. 9.]]
[[3. 4. 5. 3. 4. 5.]
 [7. 8. 9. 7. 8. 9.]]


In [12]:
a = np.array([3,4,5])
b = np.array([3,4,5])
c = np.identity(3)

# Add 2 to each element in array 'a' (also supports /, //, %, **, *)
print(a + 2)

# Compute the cosine of each element in array 'a'
print(np.cos(a))

# Compute the dot product (matrix multiplication) of array 'a' and the transpose of array 'b'
print(np.matmul(a, b.transpose()))

# Compute the determinant of the identity matrix 'c'
print(np.linalg.det(c))


[5 6 7]
[-0.9899925  -0.65364362  0.28366219]
50
1.0


# Pandas

For SQL and Pandas, if the aggregation results are incorrect and you are very sure of the logic. Often times we have forgotten to check for duplicates for the selected rows before aggregation.

Just go Stratascratch do the Hard (free) questions for mySQL and python (pandas). It is enough.. Always managed to pass Advanced SQL, Pandas questions in interviews/tests etc.

## Implement dataframe using dict and list, and types

In [46]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame(
    {
        "a": [2, 3, 4, 5],
        "b": ["a", "b", "c", "d"],
        "c": [[1, 2], [3, 4], [5, 6], [7, 8]],
    },
    # index=[0, 1, 2, 3]
)

df1

a  b       c
0  2  a  [1, 2]
1  3  b  [3, 4]
2  4  c  [5, 6]
3  5  d  [7, 8]

In [47]:
df2 = pd.DataFrame(
    [
        # different from dict implementation
        [2, "a", [1, 2]],
        [3, "b", [3, 4]],
    ],
    columns=["a", "b", "c"],
)

df2

a  b       c
0  2  a  [1, 2]
1  3  b  [3, 4]

In [48]:
print(df2.dtypes)

df2 = df2.astype({"a": float})

df2["a"] = df2["a"].apply(pd.to_numeric)
df2[["a",]] = df2[["a",]].apply(pd.to_numeric) # if multiple columns to apply function

a     int64
b    object
c    object
dtype: object


## Concat Series or dataframe

In [49]:
# Combine 2 similar df rowwise
pd.concat([df1, df2], axis=0)

a  b       c
0  2.0  a  [1, 2]
1  3.0  b  [3, 4]
2  4.0  c  [5, 6]
3  5.0  d  [7, 8]
0  2.0  a  [1, 2]
1  3.0  b  [3, 4]

In [50]:
pd.concat([df1["a"], df2["a"]], axis=1)  # works on Series too

# Combine 2 similar df colwise (*based on index)
pd.concat([df1, df2], axis=1)

a  b       c    a    b       c
0  2  a  [1, 2]  2.0    a  [1, 2]
1  3  b  [3, 4]  3.0    b  [3, 4]
2  4  c  [5, 6]  NaN  NaN     NaN
3  5  d  [7, 8]  NaN  NaN     NaN

## Melt and Pivot Transformations

In [51]:
data = {
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math_Score': [90, 85, 78],
    'English_Score': [88, 92, 80],
    'History_Score': [75, 87, 89]
}

df = pd.DataFrame(data)

df

ID     Name  Math_Score  English_Score  History_Score
0   1    Alice          90             88             75
1   2      Bob          85             92             87
2   3  Charlie          78             80             89

In [52]:
# WIDE TO LONG
melted_df = df.melt(
    id_vars = ['ID', 'Name'],
    value_vars = ['Math_Score','English_Score', 'History_Score'],
    var_name = "Subject",
    value_name = "Score"
)
melted_df

ID     Name        Subject  Score
0   1    Alice     Math_Score     90
1   2      Bob     Math_Score     85
2   3  Charlie     Math_Score     78
3   1    Alice  English_Score     88
4   2      Bob  English_Score     92
5   3  Charlie  English_Score     80
6   1    Alice  History_Score     75
7   2      Bob  History_Score     87
8   3  Charlie  History_Score     89

In [53]:
# LONG TO WIDE
long_df = melted_df.pivot(
    index=["ID", "Name"],
    columns="Subject",
    values="Score"
).reset_index().rename_axis(None, axis=1)

long_df

ID     Name  English_Score  History_Score  Math_Score
0   1    Alice             88             75          90
1   2      Bob             92             87          85
2   3  Charlie             80             89          78

## Piping functions (Sorting, renaming, dropping)

In [54]:
(
    df
    .sort_values(by=['English_Score', 'History_Score'], ascending=[False, True])
    .rename(columns = {'Name': 'Naming', 'ID': 'NRIC'})
    .drop(columns = ['NRIC'])
    .drop_duplicates()
    .reset_index(drop=True)
)

Naming  Math_Score  English_Score  History_Score
0      Bob          85             92             87
1    Alice          90             88             75
2  Charlie          78             80             89

## Sampling Values

In [55]:
df.sample(1)  # Sample 1 row

df[["Name", "Math_Score"]]  # Subset df based on col names

df["Name"]  # Series object

df.iloc[1, :3]  # i := index, else use names

df.iat[1, 3]

92

In [56]:
df.nlargest(2, "Math_Score") 
# df.nsmallest(2, "Math_Score")
# df.head(2)
# df.tail(2)

ID   Name  Math_Score  English_Score  History_Score
0   1  Alice          90             88             75
1   2    Bob          85             92             87

In [57]:
df.filter(like="Name")

Name
0    Alice
1      Bob
2  Charlie

## Filtering Functions

In [58]:
df[
    # & | ^ (and/or/xor)
    (df["Name"] == "Bob")
    & (df["English_Score"] >= 90)
    & (~df["History_Score"].isna())  # ~ flips logic or use notna()
    & (df["English_Score"].isin([90, 91, 92]))
]

df.dropna()

df["Name"] = df["Name"].fillna("0")

In [59]:
class ListNode():
    def __init__(self, val=0, next=None):

        self.val = val
        self.next = next

a = ListNode()
b = ListNode(3,a)


In [60]:
(df["Math_Score"] > 80), (df["Math_Score"] > 80).any(), (df["Math_Score"] > 80).all()
# Check series

(0     True
 1     True
 2    False
 Name: Math_Score, dtype: bool,
 True,
 False)

## Descriptive Statistics


In [61]:
df["Name"].value_counts()

Name
Alice      1
Bob        1
Charlie    1
Name: count, dtype: int64

In [62]:
len(df),
df.shape,
df["Name"].nunique()

3

In [63]:
df.describe()

ID  Math_Score  English_Score  History_Score
count  3.0    3.000000       3.000000       3.000000
mean   2.0   84.333333      86.666667      83.666667
std    1.0    6.027714       6.110101       7.571878
min    1.0   78.000000      80.000000      75.000000
25%    1.5   81.500000      84.000000      81.000000
50%    2.0   85.000000      88.000000      87.000000
75%    2.5   87.500000      90.000000      88.000000
max    3.0   90.000000      92.000000      89.000000

In [64]:
df["Math_Score"].mean()
# mean, median, count, sum, min, max, var, std, quantile([0.25,0.75])

84.33333333333333

In [65]:
# sum rowwise (add across row)
df.apply(np.sum, axis=0)


# Note for apply, if df['column'] series object, do not need specify axis, as it is single column

ID                             6
Name             AliceBobCharlie
Math_Score                   253
English_Score                260
History_Score                251
dtype: object

In [66]:
df[["Math_Score", "English_Score"]].apply(lambda x: x+30, axis=0)

Math_Score  English_Score
0         120            118
1         115            122
2         108            110

In [67]:
df["English_desc"] = df.apply(lambda row: row["Name"] + " score is " + str(row["English_Score"]), axis=1)

df

ID     Name  Math_Score  English_Score  History_Score         English_desc
0   1    Alice          90             88             75    Alice score is 88
1   2      Bob          85             92             87      Bob score is 92
2   3  Charlie          78             80             89  Charlie score is 80

## Making New Columns

In [68]:
df["Total_scores"] =  df["English_Score"] + df["History_Score"] + df["Math_Score"]

## Joins

In [69]:
data1 = {
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 22, 28]
}

df1 = pd.DataFrame(data1)

data2 = {
    'ID': [1, 2, 3, 5],
    'Name': ['Tan', 'Sim', 'Tsang', 'Lim'],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago'],
    'Occupation': ['Engineer', 'Data Scientist', 'Artist', 'Teacher']
}

df2 = pd.DataFrame(data2)

In [70]:
merged_df = pd.merge(
    df1,
    df2,
    how="outer", # outer inner right left cross
    on="ID", # left_on='ID', right_on='ID'
    indicator=True,
    suffixes= ["_left", "_right"]
)

merged_df

ID Name_left   Age Name_right           City      Occupation      _merge
0   1     Alice  25.0        Tan       New York        Engineer        both
1   2       Bob  30.0        Sim  San Francisco  Data Scientist        both
2   3   Charlie  22.0      Tsang    Los Angeles          Artist        both
3   4     David  28.0        NaN            NaN             NaN   left_only
4   5       NaN   NaN        Lim        Chicago         Teacher  right_only

## Group By Agg Functions

In [71]:
data = {
    'Date': pd.date_range(start='2022-01-01', end='2022-01-10', freq='D').tolist() * 3,
    'Product': ['A', 'B', 'C'] * 10,
    'Category': ['Electronics', 'Clothing', 'Home'] * 10,
    'Sales': np.random.randint(100, 1000, size=30),
    'Prices': np.random.randint(100, 1000, size=30),
    'Region': ['North', 'South', 'East', 'West'] * 7 + ['Central'] * 2
}

df = pd.DataFrame(data)
df.head()

Date Product     Category  Sales  Prices Region
0 2022-01-01       A  Electronics    634     745  North
1 2022-01-02       B     Clothing    635     624  South
2 2022-01-03       C         Home    916     245   East
3 2022-01-04       A  Electronics    661     948   West
4 2022-01-05       B     Clothing    224     208  North

In [72]:
pd.merge(
    df.groupby('Category')['Sales'].sum().reset_index(), # without reset_index it is a series
    df.groupby('Category')['Prices'].sum().reset_index()
)

# TO group on multiple, input a list of columns

Category  Sales  Prices
0     Clothing   5169    4410
1  Electronics   5336    5692
2         Home   6607    3831

In [73]:
df.groupby("Category")["Prices"].nlargest(2).reset_index().drop(columns=["level_1"])

Category  Prices
0     Clothing     949
1     Clothing     853
2  Electronics     998
3  Electronics     948
4         Home     944
5         Home     662

In [74]:
df['Sales_Cumsum'] = df.groupby('Category')['Sales'].cumsum() # setting column to a series with matching indexes

df.head(5)

Date Product     Category  Sales  Prices Region  Sales_Cumsum
0 2022-01-01       A  Electronics    634     745  North           634
1 2022-01-02       B     Clothing    635     624  South           635
2 2022-01-03       C         Home    916     245   East           916
3 2022-01-04       A  Electronics    661     948   West          1295
4 2022-01-05       B     Clothing    224     208  North           859

In [75]:
# IMPORTANT
df.groupby('Category')['Prices'].agg(["sum", "max"]).reset_index() # Reset the multi level index

Category   sum  max
0     Clothing  4410  949
1  Electronics  5692  998
2         Home  3831  944

## Iterating rows & Col names

In [76]:
for index, row in df.iterrows():
    print(index, row["Category"], row["Sales"])

0 Electronics 634
1 Clothing 635
2 Home 916
3 Electronics 661
4 Clothing 224
5 Home 563
6 Electronics 511
7 Clothing 371
8 Home 325
9 Electronics 149
10 Clothing 558
11 Home 426
12 Electronics 521
13 Clothing 710
14 Home 522
15 Electronics 906
16 Clothing 126
17 Home 705
18 Electronics 378
19 Clothing 960
20 Home 624
21 Electronics 696
22 Clothing 487
23 Home 819
24 Electronics 210
25 Clothing 407
26 Home 778
27 Electronics 670
28 Clothing 691
29 Home 929


In [77]:
df.columns

Index(['Date', 'Product', 'Category', 'Sales', 'Prices', 'Region',
       'Sales_Cumsum'],
      dtype='object')

## Handling datetime

In [78]:
import pandas as pd

df = pd.DataFrame({'date': ['2022-01-01', '02/03/2022', '03/01/2022']})

df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d', errors='coerce')

df

date
0 2022-01-01
1        NaT
2        NaT

In [79]:
df['date'].dt.strftime('%m')

0     01
1    NaN
2    NaN
Name: date, dtype: object

In [80]:
df = pd.DataFrame({
    "created_at": pd.date_range(start="2022-01-01", periods=100),
    "category": np.random.choice(['A', 'B', 'C'], size=100),
    "Value1": np.random.randint(1, 101, size=100),
    "Value2": np.random.normal(0, 1, 100),
})

In [81]:
df['year_month'] = df["created_at"].dt.strftime('%Y-%m')

df.head(3)

created_at category  Value1    Value2 year_month
0 2022-01-01        B      92  0.209360    2022-01
1 2022-01-02        B      66 -0.145118    2022-01
2 2022-01-03        B      74  0.248830    2022-01

## Lag and Lead

In [82]:
df["Value1_lag"] = df['Value1'].shift(periods=1, fill_value=0)
df.head(3)

created_at category  Value1    Value2 year_month  Value1_lag
0 2022-01-01        B      92  0.209360    2022-01           0
1 2022-01-02        B      66 -0.145118    2022-01          92
2 2022-01-03        B      74  0.248830    2022-01          66

In [88]:
df["Value2_lag_by_category"] = df.groupby('category')['Value2'].shift(periods=1, fill_value=0)
df.head(3)

created_at category  Value1    Value2 year_month  Value1_lag  \
0 2022-01-01        B      92  0.209360    2022-01           0   
1 2022-01-02        B      66 -0.145118    2022-01          92   
2 2022-01-03        B      74  0.248830    2022-01          66   

   Value2_lag_by_category  
0                0.000000  
1                0.209360  
2               -0.145118

## Standardizing

In [ ]:
df["std_Value2"] = df.groupby('category')['Value2'].transform(lambda x: (x-x.mean())/x.std())

## Percentile & Ranking

In [38]:
df["percentile"] = df.groupby(['category'])['Value2'].rank(pct = True) # pct returns the percentile form

df[df["percentile"] > 0.95]

created_at category  Value1    Value2 year_month  Value1_lag  \
28 2022-01-29        C      34  2.741430    2022-01          87   
29 2022-01-30        B      98  1.948840    2022-01          34   
47 2022-02-17        A      31  2.442694    2022-02          76   
51 2022-02-21        B      90  1.841580    2022-02          47   
89 2022-03-31        A      27  0.982400    2022-03          66   
94 2022-04-05        C      31  2.371341    2022-04          94   

    Value2_lag_by_category  std_Value2  percentile  
28                1.369396    2.279343    1.000000  
29               -1.117669    1.837313    1.000000  
47               -1.851729    2.926903    1.000000  
51                0.198765    1.739704    0.974359  
89               -0.804674    1.333645    0.967742  
94               -1.076970    1.951188    0.966667

In [39]:
# MySQL -- DENSE_RANK() does not skip NUMBER 1 1 2 3
# MySQL -- RANK() skips number e.g. 1 1 3 4
# Pandas -- dense
# Pandas -- min

df["ranking"] = df.groupby(['category'])['Value1'].rank(ascending=False, method='dense')

df[df["ranking"] >= 2].head(3)

created_at category  Value1    Value2 year_month  Value1_lag  \
0 2022-01-01        B      47 -0.223794    2022-01           0   
1 2022-01-02        B      27 -1.645556    2022-01          47   
2 2022-01-03        A      26  0.206114    2022-01          27   

   Value2_lag_by_category  std_Value2  percentile  ranking  
0                0.000000   -0.139833    0.435897     18.0  
1               -0.223794   -1.433669    0.102564     25.0  
2                0.000000    0.486675    0.741935     20.0

# Sklearn

In [99]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

from sklearn.datasets import load_breast_cancer

sample_data = load_breast_cancer()

X = pd.DataFrame(sample_data.data, columns=sample_data.feature_names)
y = pd.Series(sample_data.target)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

model = LogisticRegression(random_state=42, max_iter=3000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

acc = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='binary') # if not binary need things like weighted
recall = recall_score(y_test, y_pred, average='binary') # if not binary need things like weighted
f1 = f1_score(y_test, y_pred, average='binary') # if not binary need things like weighted

In [101]:
TP = sum((y_test.iloc[i] == 1 and y_pred[i] == 1) for i in range(len(y_test)))
TN = sum((y_test.iloc[i] == 0 and y_pred[i] == 0) for i in range(len(y_test)))
FP = sum((y_test.iloc[i] == 0 and y_pred[i] == 1) for i in range(len(y_test)))
FN = sum((y_test.iloc[i] == 1 and y_pred[i] == 0) for i in range(len(y_test)))

accuracy = (TP + TN) / (len(y_test))
precision = TP / (TP + FP) if (TP + FP) != 0 else 0
recall = TP / (TP + FN) if (TP + FN) != 0 else 0
f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) != 0 else 0

In [64]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.ensemble import RandomForestRegressor

data = {
    "Color": ["Red", "Blue", "Green", "Blue", "Red", "Green", "Blue", "Red"],
    "Size": [1, 2, 3, 2, 1, 3, 2, 1],
    "Weight": [10.5, 12.3, 15.1, 11.8, 9.6, 14.2, 13.4, 10.1],
}

sample_data = pd.DataFrame(data)

X = sample_data.iloc[:,1:]
y = sample_data.iloc[:,0:1]

encoder = OrdinalEncoder()

y = encoder.fit_transform(y) # produces a column vector of n by 1

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)

model = RandomForestRegressor(random_state=42)

model.fit(X_train, y_train.ravel()) # ravel converts to 1 by n

y_pred = np.ceil(model.predict(X_test))

precision = precision_score(y_test, y_pred, average='weighted')
